### ISSUE TITLE
"parsingFunctions.R" Does this script only apply to HLA-HD results?

### ISSUE THREAD

**Issue by jingydz** [Genentech/midasHLA#17]
Hi, I have a question. Is the script "parsingfunctions. R" only applicable to HLA-HD results?
**na.strings = c("Not typed", "-", "NA")**
In HLA-HD software, "-" does not stand for NA, but for homozygous.
In addition, for some alleles, it's going to be the same thing as the "read result file.", which should be done?
Looking forward to your reply, thank you!

Best
Jing

**Comment by chammer80** [comment]
Hi @jingydz,

different HLA inference tools output results in slightly different ways, and I agree that the way HLA-HD deals with homozygous calls is not optimal. In our internal inference pipeline, we automatically modify the output to reflect the actual genotypes, and MiDAS has not been developed to be compatible with a specific HLA inference tool. In this case, it expects both alleles to be named in case of homozygosity, and strings such as "NA" or "-" will indeed be considered "NA".
