### ISSUE TITLE
connection timeout when downloading latest datasets

### ISSUE THREAD

**Issue by fmobegi** [Genentech/midasHLA#18]
Am trying to update the datasets from `http://www.allelefrequencies.net` but the script keeps timing in less than 5 minutes. Is it possible to update the frequency dataset in your repository?

**Comment by mcjmigdal** [comment]
@fmobegi sorry for extremely late response I totally missed your issue. I will look into this next week.

**Comment by mcjmigdal** [comment]
allele and kir database updated 11bde30cbbf11b34f2dea29a6284371a9c1e9440
