### ISSUE TITLE
Error in approx(sp$y, sp$x, xout = cutoff) :    need at least two non-NA values to interpolate

### ISSUE THREAD

**Issue by bri2020** [Genentech/midasHLA#20]
Dear midasHLA authors,

I am start exploring your R-package. Is it possible to subset your scripts to certain HLA genes, in case not all genes/alleles has been typed? 
E.g. I am getting an error: 
```
HLA_het_results <- runMiDAS(HLA_het_model, 
+   experiment = "hla_het", 
+   exponentiate = TRUE
+ )
Warning: 'experiments' dropped; see 'metadata'Error in approx(sp$y, sp$x, xout = cutoff) : 
  need at least two non-NA values to interpolate
```
or 
```
> HLA_div_results <- runMiDAS(HLA_het_model, 
+   experiment = "hla_divergence", 
+   exponentiate = FALSE
+ )
Error in approx(sp$y, sp$x, xout = cutoff) : 
  need at least two non-NA values to interpolate
```
Could this be due to my high missigness, eg. at the DPB1 locus, even divergences isn't computed with class II genes?
```
 midasHLA::getAlleleResolution(dat_HLA_example$DPB1_1)
 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA  4 NA  4 NA  4 NA  4 NA NA NA  4 NA NA
```
If yes, can I use your package without some of the  MHC (class II) genes? Would be great if there would be a function to exclude specific loci.

Thanks a lot,
Britta

PS. Let me know if you need further information to answer my question or evaluate my error message

**Comment by mcjmigdal** [comment]
Hi Britta,

thank you for reporting this issue!
Would it be possible for you to provide some example input file? That would help me a lot to figure out what is happening. It does not need to be large ~50 lines should do it.

**Comment by mcjmigdal** [comment]
@bri2020 additionally, how do you specify you model (`HLA_het_model`)?

**Comment by bri2020** [comment]
Dear Midgal,
Thanks a a lot for your quick answer and help offered. I had been exploring my fake data and error myself and realized that there was to few (none) variability in my fake outcome/disease. When I added more realistic (random) data, this error disappeared. Thanks so much again.
