### ISSUE TITLE
KIR module

### ISSUE THREAD

**Issue by Pharmacogenetecist** [Genentech/midasHLA#22]
Hello folks,
Thank you for creating a very useful package for HLA analysis.

I have recently been using a tool to extract KIR genotypes (T1K). The output for one sample looks as below. I have been advised that in the case of 1 below, it is a homozygote.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/smaggo/AppData/Local/Temp/Mxt220/var/log/xwin/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/smaggo/AppData/Local/Temp/Mxt220/var/log/xwin/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

GENE | Alleles | 1 | 2
-- | -- | -- | --
KIR2DL1 | 2 | KIR2DL1*004 | KIR2DL1*003
KIR2DL2 | 1 | KIR2DL2*001 | .
KIR2DL3 | 1 | KIR2DL3*001 | .
KIR2DL4 | 2 | KIR2DL4*008 | KIR2DL4*005
KIR2DL5A | 2 | KIR2DL5A*029 | KIR2DL5A*001
KIR2DL5B | 2 | KIR2DL5B*002 | KIR2DL5B*004
KIR2DP1 | 2 | KIR2DP1*002 | KIR2DP1*001
KIR2DS1 | 1 | KIR2DS1*002 | .
KIR2DS2 | 1 | KIR2DS2*001 | .
KIR2DS3 | 1 | KIR2DS3*001 | .
KIR2DS4 | 2 | KIR2DS4*003 | KIR2DS4*001
KIR2DS5 | 1 | KIR2DS5*002 | .
KIR3DL1 | 1 | KIR3DL1*001 | .
KIR3DL2 | 2 | KIR3DL2*007 | KIR3DL2*001
KIR3DL3 | 2 | KIR3DL3*014 | KIR3DL3*002
KIR3DP1 | 1 | KIR3DP1*003 | .
KIR3DS1 | 1 | KIR3DS1*013 | .

</body>

</html>

However the KIR module looks like it only allows a 1/0 value, and in addition there is not an option to enter allele_1 and allele_2 like the HLA module.

Thank you.

**Comment by mcjmigdal** [comment]
Hi @Pharmacogenetecist, 

indeed the `midasHLA` package does allow to use only **gene level KIR calls**. If I recall correctly, when we were developing the package there was no tools capable of calling KIRs at the allele resolution.

As for allowing only 1/0 values, I don't think this is true. At least I don't see any code in the package that would force this.
See the following dummy example
```
> dat_pheno <-
  read.table(
  file = system.file("extdata", "MiDAS_tut_pheno.txt", package = "midasHLA"),
  header = TRUE
  )
> dat_KIR <- readKirCalls(
  file = system.file("extdata", "MiDAS_tut_KIR.txt", package = "midasHLA")
)
> dat_KIR[, 2] <- dat_KIR[, 2] + 5 # here I make it non 0/1
> HLA <- prepareMiDAS(    
  kir_calls = dat_KIR,
  colData = dat_pheno,                                                       
  experiment = "kir_genes"
)
> HLA_results <- runMiDAS(
  object = HLA_model, 
  experiment = "kir_genes",  
  correction = "bonferroni", 
  exponentiate = TRUE
)
> head(HLA_results)
# A tibble: 6 × 14
  kir.g…¹ p.value p.adj…² estim…³ std.e…⁴ conf.…⁵ conf.…⁶ stati…⁷ Ntotal Ntota…⁸
  <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>  <dbl> <formt>
1 KIR3DL1 3.65e-6 5.84e-5   3.43    0.266   2.07    5.91     4.63    853 91.23% 
2 KIR2DS4 3.65e-6 5.84e-5   3.43    0.266   2.07    5.91     4.63    853 91.23% 
3 KIR2DL3 4.41e-2 7.06e-1   0.628   0.231   0.396   0.983   -2.01    849 90.80% 
4 KIR2DS2 8.29e-2 1   e+0   1.26    0.131   0.971   1.62     1.73    455 48.66% 
5 KIR2DL2 1.09e-1 1   e+0   1.23    0.131   0.955   1.60     1.60    449 48.02% 
6 KIR2DS5 1.14e-1 1   e+0   0.799   0.142   0.605   1.06    -1.58    288 30.80% 
# … with 4 more variables: `N(disease=0)` <dbl>,
#   `N(disease=0).percent` <formttbl>, `N(disease=1)` <dbl>,
#   `N(disease=1).percent` <formttbl>, and abbreviated variable names
#   ¹​kir.gene, ²​p.adjusted, ³​estimate, ⁴​std.error, ⁵​conf.low, ⁶​conf.high,
#   ⁷​statistic, ⁸​Ntotal.percent
# ℹ Use `colnames()` to see all variable names
```

Going back to the issue you are facing, I think one option you could consider is to summarize your KIR allele data to the gene level, that would allow you to use our standard workflow.

As for the adding new functionality to handle KIR allele calls, this needs a bit more consideration. Could you let me know which software did you use for KIR calling?

@chammer80 do you have any thoughts on KIR analysis at the allele level?

**Comment by Pharmacogenetecist** [comment]
> Hi @Pharmacogenetecist,
> 
> indeed the `midasHLA` package does allow to use only **gene level KIR calls**. If I recall correctly, when we were developing the package there was no tools capable of calling KIRs at the allele resolution.
> 
> As for allowing only 1/0 values, I don't think this is true. At least I don't see any code in the package that would force this. See the following dummy example
> 
> ```
> > dat_pheno <-
>   read.table(
>   file = system.file("extdata", "MiDAS_tut_pheno.txt", package = "midasHLA"),
>   header = TRUE
>   )
> > dat_KIR <- readKirCalls(
>   file = system.file("extdata", "MiDAS_tut_KIR.txt", package = "midasHLA")
> )
> > dat_KIR[, 2] <- dat_KIR[, 2] + 5 # here I make it non 0/1
> > HLA <- prepareMiDAS(    
>   kir_calls = dat_KIR,
>   colData = dat_pheno,                                                       
>   experiment = "kir_genes"
> )
> > HLA_results <- runMiDAS(
>   object = HLA_model, 
>   experiment = "kir_genes",  
>   correction = "bonferroni", 
>   exponentiate = TRUE
> )
> > head(HLA_results)
> # A tibble: 6 × 14
>   kir.g…¹ p.value p.adj…² estim…³ std.e…⁴ conf.…⁵ conf.…⁶ stati…⁷ Ntotal Ntota…⁸
>   <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>  <dbl> <formt>
> 1 KIR3DL1 3.65e-6 5.84e-5   3.43    0.266   2.07    5.91     4.63    853 91.23% 
> 2 KIR2DS4 3.65e-6 5.84e-5   3.43    0.266   2.07    5.91     4.63    853 91.23% 
> 3 KIR2DL3 4.41e-2 7.06e-1   0.628   0.231   0.396   0.983   -2.01    849 90.80% 
> 4 KIR2DS2 8.29e-2 1   e+0   1.26    0.131   0.971   1.62     1.73    455 48.66% 
> 5 KIR2DL2 1.09e-1 1   e+0   1.23    0.131   0.955   1.60     1.60    449 48.02% 
> 6 KIR2DS5 1.14e-1 1   e+0   0.799   0.142   0.605   1.06    -1.58    288 30.80% 
> # … with 4 more variables: `N(disease=0)` <dbl>,
> #   `N(disease=0).percent` <formttbl>, `N(disease=1)` <dbl>,
> #   `N(disease=1).percent` <formttbl>, and abbreviated variable names
> #   ¹​kir.gene, ²​p.adjusted, ³​estimate, ⁴​std.error, ⁵​conf.low, ⁶​conf.high,
> #   ⁷​statistic, ⁸​Ntotal.percent
> # ℹ Use `colnames()` to see all variable names
> ```
> 
> Going back to the issue you are facing, I think one option you could consider is to summarize your KIR allele data to the gene level, that would allow you to use our standard workflow.
> 
> As for the adding new functionality to handle KIR allele calls, this needs a bit more consideration. Could you let me know which software did you use for KIR calling?
> 
> @chammer80 do you have any thoughts on KIR analysis at the allele level?

Thank you for your response and looking into this.
I used the following tool to KIR type my Exome date - https://github.com/mourisl/T1K

**Comment by chammer80** [comment]
Hi @Pharmacogenetecist,
We indeed made the decision to only consider presence/absence calls for KIRs, based on the availability of KIR typing tools at that point in time. We've mainly been using Dave Roe's kpi (https://github.com/droeatumn/kpi) for KIR typing, but it requires WGS.
T1k is novel, and while I think it's a great tool and really promising, I'm not sure regarding the validation of the KIR typing data, especially on allele level, since there's not too much reference data available. Plus, KIR/HLA interactions are most established on KIR gene level, but maybe the availability of tools like T1k will change that and require an update of MiDAS at some point.
In any case, to use MiDAS with your data at this point in time, you'd have to modify your KIR typing results to indicate KIR gene presence / absence (1/0). 
Hope this helps.

**Comment by Pharmacogenetecist** [comment]
> Hi @Pharmacogenetecist, We indeed made the decision to only consider presence/absence calls for KIRs, based on the availability of KIR typing tools at that point in time. We've mainly been using Dave Roe's kpi (https://github.com/droeatumn/kpi) for KIR typing, but it requires WGS. T1k is novel, and while I think it's a great tool and really promising, I'm not sure regarding the validation of the KIR typing data, especially on allele level, since there's not too much reference data available. Plus, KIR/HLA interactions are most established on KIR gene level, but maybe the availability of tools like T1k will change that and require an update of MiDAS at some point. In any case, to use MiDAS with your data at this point in time, you'd have to modify your KIR typing results to indicate KIR gene presence / absence (1/0). Hope this helps.

Thank you appreciate the response.
MiDAS is a great tool!
