### ISSUE TITLE
HLA allele frequency by phenotype/disease

### ISSUE THREAD

**Issue by BioinformaNicks** [Genentech/midasHLA#23]
Hi authors,

Is it possible to calculate the HLA frequencies per phenotype (i.e. disease) from the total?
I would like to create a figure for this.

Kind regards

**Comment by mcjmigdal** [comment]
Hi BioinformaNicks

I think this is provided in runMiDAS output?
From the [tutorial](https://genentech.github.io/midasHLA/articles/MiDAS_tutorial.html#are-classical-hla-alleles-associated-with-disease-status):

![Screenshot_20231015-192241-744](https://github.com/Genentech/midasHLA/assets/22835660/6f1b92fd-0376-436e-991f-4b7c3854ad6f)
 
Is this what you had in mind?

**Comment by BioinformaNicks** [comment]
> Hi BioinformaNicks
> 
> I think this is provided in runMiDAS output? From the [tutorial](https://genentech.github.io/midasHLA/articles/MiDAS_tutorial.html#are-classical-hla-alleles-associated-with-disease-status):
> 
> ![Screenshot_20231015-192241-744](https://user-images.githubusercontent.com/22835660/275342884-6f1b92fd-0376-436e-991f-4b7c3854ad6f.png)
> 
> Is this what you had in mind?

Hi mcjmigdal,

While this would indeed technically work, this would only be after running the association analysis with pre-set thresholds.
It could be useful to have an extra argument to getFrequencies() that could specificy a 'split-by', and the output would be two rows of for example A*03:01 with a count per phenotype and a frequency of the total (or within-phenotype?)?

**Comment by mcjmigdal** [comment]
@BioinformaNicks the code that calculates 'HLA frequencies per phenotype' for `runMiDAS` output is actually wrapped in an internal function called `runMiDASGetVarsFreq`. It was not intended to be a user-level function, but I think you can give it a try :cowboy_hat_face:  

 `runMiDASGetVarsFreq` works with `MiDAS` objects so it can be used after creating one, but prior to running the actual analysis. It has a manual page in case you need it. You can try the following:

```
library(midasHLA)
dat_pheno <-
  read.table(
  file = system.file("extdata", "MiDAS_tut_pheno.txt", package = "midasHLA"),
  header = TRUE
  )
dat_HLA <-
  readHlaCalls(
  file = system.file("extdata", "MiDAS_tut_HLA.txt", package = "midasHLA"),
  resolution = 4
  )
HLA <- prepareMiDAS(
  hla_calls = dat_HLA,
  colData = dat_pheno,                                                       
  experiment = "hla_alleles"
 )
freqs <- midasHLA:::runMiDASGetVarsFreq(HLA, 'hla_alleles', 'disease')
head(freqs)

# the result is a data.frame and should look like this
# term Ntotal Ntotal.percent N(disease=0) N(disease=0).percent N(disease=1) N(disease=1).percent
# A*01:01    236         11.80%          116               11.60%          120 12.00%
# A*01:02      2          0.10%            0                0.00%            2 0.20%
# ...
```

Let me know how it goes. If it is useful we could consider exposing it to user interface.
