### ISSUE TITLE
inference of amino acids 

### ISSUE THREAD

**Issue by bsb2014** [Genentech/midasHLA#25]
The publication mentions "MiDAS facilitates this process by inferring variable amino acid residues for all imported individuals with HLA allele data".  Could you please tell me more how MiDAS infers the AA based on HLA alleles? Is any reference panel used? Thanks

**Comment by mcjmigdal** [comment]
hi @bsb2014 

No reference panel is used, this is done from the data. First HLA allele level information is translated to amino acid sequence. Then the positions that show any variability are found, these can be further tested using omnibus test.

Take a look at our [tutorial](https://genentech.github.io/midasHLA/articles/MiDAS_tutorial.html#hla-association-fine-mapping-on-amino-acid-level) and documentation ([prepareMiDAS](https://genentech.github.io/midasHLA/reference/prepareMiDAS.html), [hlaToAAVariation](https://genentech.github.io/midasHLA/reference/hlaToAAVariation.html), [omnibusTest](https://genentech.github.io/midasHLA/reference/omnibusTest.html)).

**Comment by bsb2014** [comment]
Does MiDAS leverage the IPD-IMGT/HLA to translate HLA alleles to amino acid sequences? Thanks

**Comment by bsb2014** [comment]
In the association result, which one is the effect size, estimate or statistic? Thanks

**Comment by bsb2014** [comment]
If I  would like to add covariates,  which one is correct? thanks

no covariates
HLA_model <- glm(disease ~ term, data = HLA, family = binomial())

covariates

HLA_model <- glm(disease ~ term + age, data = HLA, family = binomial())
or 
HLA_model <- glm(disease ~ age + term, data = HLA, family = binomial())

**Comment by mcjmigdal** [comment]
I recommend you reading our documentation, the tutorial and also [Quick start](https://genentech.github.io/midasHLA/articles/MiDAS_vignette.html#running-analysis) should provide you with all the answers.

`
HLA_model <- glm(disease ~ term + age, data = HLA, family = binomial())
or
HLA_model <- glm(disease ~ age + term, data = HLA, family = binomial())
`

I guess both should be equivalent, is there any difference in the results?
