### ISSUE TITLE
Divergaed version numbering in BioC repository

### ISSUE THREAD

**Issue by mcjmigdal** [Genentech/midasHLA#27]
hi, i realized the version numbering diverged, in the BioC it is 1.10 and here it was 1.5.3. I have investigated this and actually these is related to BioC lifecycle, they bump packages versions even if no changes were made. Because this repo is seperate from bioconductor the version change is not propagated to this repository. An easy fix is to use github action to merge changes from BioC repository.

c335644a0637c000b7cbc85a4f3b5ae86a76680e, e06c90211e349daa890830b694ffa894eeed3610

**Comment by LiNk-NY** [comment]
Note that our releases occur once every 6 months. 
A GitHub Action to pull from the Bioconductor git repository (`upstream`) would fail for nearly all of the year.
It is best to sync your GitHub repository with `upstream` at every release or use the [ReleaseLaunch](https://github.com/Bioconductor/ReleaseLaunch) package if you are maintaining a significant number of packages.

**Comment by mcjmigdal** [comment]
@LiNk-NY 

For my purposes I will go with schedule controlled action to compare latest bioconductor commit with github history. I guess this could repurposed to check for your file modification.

```
on:
  schedule:
    - cron: "30 8 * * *"

name: syncronise-bioconductor-release

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BIOC_REMOTE='https://git.bioconductor.org/packages/midasHLA'
          MAIN_BRANCH='master'
          COMMIT_TITLE='New Bioconductor release'
          gitlog() {
            git --no-pager log --pretty=format:'%h' ${@}
          }
          git remote add bioconductor ${BIOC_REMOTE}
          git fetch bioconductor
          BIOC_TAG=`gitlog bioconductor/master -1`
          COMMIT_BODY=`git --no-pager log bioconductor/master --pretty=format:'%s' -1`
          if [[ gitlog ${MAIN_BRANCH} | grep -q -e ${BIOC_TAG} ]]; then
            git checkout bioconductor/master
            gh pr create --base master --title "${COMMIT_TITLE}" --body "${COMMIT_BODY}"
          fi
```

I am still testing this solution, happy to get your comments ;)

**Comment by LiNk-NY** [comment]
Hi Migdal, @mcjmigdal 

Is it supposed to run every day at 8:30 AM? The frequency seems a bit too much.
Note that the release happens once every six months between May-April and October-November as seen on https://bioconductor.org/about/release-announcements/. It would be great if the chron job could be updated according to that. 

I was also expecting it to simply `git pull` the upstream changes and `git push` into the GitHub `devel` branch and not create a PR. 

Thanks for sharing!

**Comment by mcjmigdal** [comment]
@LiNk-NY thanks for the feedback!

Ineed, I am considering to fire it up once a month or twice a year but I need to investigate how stable are BioC release dates.

**Comment by mcjmigdal** [comment]
2879a745441714eb81ec0b72fdd7227c8a4c1a4e
