### ISSUE TITLE
How to add covariate information into glm model with midas object

### ISSUE THREAD

**Issue by alicekiki** [Genentech/midasHLA#28]
I want to include covariate info when doing association analysis, but there is no such option in prepareMIDAS, and the glm model is directly based on this object, any method to include it? Thank you for ur time~
<img width="489" alt="image" src="https://github.com/Genentech/midasHLA/assets/87300300/6cac3292-2f14-4aef-8c6c-71e503bde221">

**Comment by mcjmigdal** [comment]
This was somewhere in the doc but I can't find it right now

Basically, you just add your covariates to your model and you can use any variable from the colData eg. `glm(disease ~ age + term, ...)`

There was also some questions about recently  https://github.com/Genentech/midasHLA/issues/25#issuecomment-1805781680

**Comment by alicekiki** [comment]
> This was somewhere in the doc but I can't find it right now
> 
> Basically, you just add your covariates to your model and you can use any variable from the colData eg. `glm(disease ~ age + term, ...)`
> 
> There was also some questions about recently [#25 (comment)](https://github.com/Genentech/midasHLA/issues/25#issuecomment-1805781680)

Thanks for your reply, really appreciate it~
