### ISSUE TITLE
Explanation of the result

### ISSUE THREAD

**Issue by bsb2014** [Genentech/midasHLA#33]
I got a result below

• Coefficients for variables: DRB1_47_Y could not be estimated, those variables will not be included in likelyhood ratio test result.; occured 1 times, including variables: DRB1_47_F

......
 aa_pos  residues            df statistic  p.value p.adjusted
 DRB1_47 F                    1      6.35 0.0117      0.376
.....

I expected at least two residues in the second column but only one "F". Could you please give me some suggestions for this situation? Thanks

I also found a similar result in your tutorial

DQB1_23 | R | 1 | 2.777e+00 | 9.565e-02 | 1.000e+00

Edited: I found that not all residues are listed in the second column

**Comment by bsb2014** [comment]
By the way, the model with covariates is extremely slower compared with the no-covariate model.

**Comment by mcjmigdal** [comment]
Could you give some example code for how you run these models?

**Comment by bsb2014** [comment]
library(midasHLA)

dat_pheno <- read.table("HLA-DRB1.phno.txt", header=T)
dat_HLA <- readHlaCalls("HLA-DRB1.geno.txt", resolution = 4)
HLA_AA <- prepareMiDAS(
  hla_calls = dat_HLA,
  colData = dat_pheno,
  experiment = "hla_aa"
)

HLA_AA_model <- glm(case_control  ~ term, data = HLA_AA, family = binomial())
HLA_AA_omnibus_results <- runMiDAS( HLA_AA_model, experiment = "hla_aa", inheritance_model = "additive", conditional = FALSE, omnibus = TRUE, lower_frequency_cutoff = 0.02, upper_frequency_cutoff = 0.98, correction = "bonferroni" )
The no-covariate model can be finished within several minutes. 


HLA_AA_model <- glm(case_control  ~ Age+Sex+asma+term, data = HLA_AA, family = binomial())
HLA_AA_omnibus_results <- runMiDAS( HLA_AA_model, experiment = "hla_aa", inheritance_model = "additive", conditional = FALSE, omnibus = TRUE, lower_frequency_cutoff = 0.02, upper_frequency_cutoff = 0.98, correction = "bonferroni" )
The covariate model is stuck at runMiDAS 


If model with covariate is used, will the midasHLA extract the coefficients for term only?

**Comment by bsb2014** [comment]
In your tutorial (https://genentech.github.io/midasHLA/articles/MiDAS_tutorial.html), some results also only show one residue in the second column, such as


DQB1_23 | R | 1 | 2.777e+00 | 9.565e-02 | 1.000e+00
B_109 | L | 1 | 1.387e+00 | 2.389e-01 | 1.000e+00

I supposed at least two residues there. Thanks.

**Comment by mcjmigdal** [comment]
I have some ideas about your problems but I cannot reproduce this. Could you recreate your workflow on tutorial's data so I can recreate?

What is term in your model? 
For the omnibus test it is my understanding that you need to provide the omnibus_groups, which I think you are not doing?

**Comment by bsb2014** [comment]
I supposed the "term" was replaced by each tested amino acid automatically for the likelihood ratio (omnibus) test. I am probably wrong. 

I will use the tutorial's data to test a model with covariates.

**Comment by bsb2014** [comment]
Solved. There are some dots (.) in the Age column. It worked well after removing them.

**Comment by mcjmigdal** [comment]
> I supposed the "term" was replaced by each tested amino acid automatically for the likelihood ratio (omnibus) test. I am probably wrong.

No you are right! I was trying to figure out what is going on.
