### ISSUE TITLE
function omnibus_groups_filter

### ISSUE THREAD

**Issue by bsb2014** [Genentech/midasHLA#36]
Can I set a reference amino acid and tested amino acids to calculate effect estimates at a given amino acid position?

For example, at position B_97 (an example in https://genentech.github.io/midasHLA/articles/MiDAS_tutorial.html),  there are six amino acids B_97_S	B_97_R	B_97_T	B_97_N	B_97_V	B_97_W. 
The following table was generated by prepareMiDAS (an example in https://genentech.github.io/midasHLA/articles/MiDAS_tutorial.html)
B_97_S | B_97_R | B_97_T | B_97_N | B_97_V | B_97_W
C001 | 1 | 1 | 0 | 0 | 0 | 0
C002 | 0 | 2 | 0 | 0 | 0 | 0
C003 | 0 | 1 | 1 | 0 | 0 | 0
C004 | 1 | 1 | 0 | 0 | 0 | 0
C005 | 1 | 1 | 0 | 0 | 0 | 0
C006 | 2 | 0 | 0 | 0 | 0 | 0

If I would use the B_97_R as the reference against B_97_S (to be tested), so only S/S,S/R,R/R amino acids will be kept and the sample C003 will be removed for the regression.

Thanks

**Comment by mcjmigdal** [comment]
Hi @bsb2014 I am not sure if I fully understand what do you mean by using B_97_R as a reference against B_97_S. What is the question that you are trying to answer?

**Comment by mcjmigdal** [comment]
Yes, for each patient/sample (rows) it gives you information on the residues (columns) counts at position B_97.

**Comment by bsb2014** [comment]
I think the counts will be used for the regression as the effect residues (as GWAS, there are effect and reference SNPs) if the additive model is used. 

For example, we use the column B_97_R as the effect residue for the regression, and the reference residues will be all other  B_97S,B_97T,B_97N,B_97V,B_97W.

Now, I would like to use the column B_97_R as the effect residue and only B_97_S as the reference residue (assume this residue is the most common). Then, because C003 only has residues RT (not RR,SS,RS), it will not be used for the regression.

 B_97_S | B_97_R | B_97_T | B_97_N | B_97_V | B_97_W
C001 | 1 | 1 | 0 | 0 | 0 | 0
C002 | 0 | 2 | 0 | 0 | 0 | 0
C003 | 0 | 1 | 1 | 0 | 0 | 0
C004 | 1 | 1 | 0 | 0 | 0 | 0
C005 | 1 | 1 | 0 | 0 | 0 | 0
C006 | 2 | 0 | 0 | 0 | 0 | 0

Thanks
