### ISSUE TITLE
getAllelesForAA

### ISSUE THREAD

**Issue by bsb2014** [Genentech/midasHLA#42]
###########error##########
getAllelesForAA(HLA_AA,"DQB1_77")
Error: allele DQB1*02:180 could not be found in the alignment file
Execution halted
#######################

I expected that midasHLA would still output other available alleles even if one HLA allele is missing. Thanks!

**Comment by mcjmigdal** [comment]
@bsb2014 would it be possible for you to provide a reproducible example?
