### ISSUE TITLE
 high-resolution KIR alleles analyses

### ISSUE THREAD

**Issue by Eduardo-Auer** [Genentech/midasHLA#45]
Hello! I am very pleased to have found this package, as it simplifies the process of HLA allele association with covariates correction and conditional analyses. I would like to know if these methods will be available for KIR alleles, as I will soon have high-resolution KIR allele genotyping.

**Comment by mcjmigdal** [comment]
There are no plans to extend the package to accommodate high-resolution KIR alleles. See #22

**Comment by Eduardo-Auer** [comment]
Ok, I understand. Thanks for the response.
